import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { poppins } from "@/public/fonts";
import "./globals.css";

export const metadata: Metadata = {
	title: "Flourence Lapore",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased`}>{children}</body>
		</html>
	);
}
